[package]
name = "resource"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

# Local dev-dependencies
test-utils = { workspace = true }

[dependencies]
actix-rt = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bitflags = "1.2.1"
byte-unit = "4.0.14"
cgroups-rs = "0.3.2"
futures = "0.3.11"
lazy_static = { workspace = true }
libc = { workspace = true }
netns-rs = { workspace = true }
netlink-sys = "0.8.3"
netlink-packet-route = "0.19.0"
nix = { workspace = true }
rand = { workspace = true }
rtnetlink = "0.14.0"
scopeguard = "1.0.0"
serde = { workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
slog-scope = { workspace = true }
tokio = { workspace = true, features = ["process"] }
tracing = { workspace = true }
uuid = { version = "0.4", features = ["v4"] }
oci-spec = { workspace = true }

# Local dependencies
agent = { workspace = true }
hypervisor = { workspace = true }
kata-types = { workspace = true }
kata-sys-util = { workspace = true }
logging = { workspace = true }
persist = { workspace = true }
tests_utils = { workspace = true }

[features]
