[package]
name = "virt_container"
version = "0.1.0"
authors = ["The Kata Containers community <kata-dev@lists.katacontainers.io>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
anyhow = "^1.0"
async-trait = "0.1.48"
awaitgroup = "0.6.0"
containerd-shim-protos = { version = "0.6.0", features = ["async"] }
futures = "0.3.19"
lazy_static = "1.4.0"
libc = ">=0.2.39"
nix = "0.24.2"
protobuf = "=3.7.1"
sendfd = { version = "0.4.3", features = ["tokio"] }
serde = { version = "1.0.100", features = ["derive"] }
serde_derive = "1.0.27"
serde_json = "1.0.82"
slog = "2.5.2"
slog-scope = "4.4.0"
tokio = { version = "1.38.0" }
toml = "0.4.2"
url = "2.1.1"
async-std = "1.12.0"
tracing = "0.1.36"
oci-spec = { version = "0.6.8", features = ["runtime"] }
strum = { version = "0.24.0", features = ["derive"] }

# Local dependencies
agent = { workspace = true }
common = { workspace = true }
hypervisor = { workspace = true, features = ["cloud-hypervisor"] }
kata-sys-util = { workspace = true }
kata-types = { workspace = true }
logging = { workspace = true }
runtime-spec = { workspace = true }
persist = { workspace = true }
resource = { workspace = true }

[features]
default = ["cloud-hypervisor"]

# Enable the Cloud Hypervisor driver
cloud-hypervisor = []

# Enable the build-in VMM Dragtonball
dragonball = []
